# Generated by Django 5.2.3 on 2025-07-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0005_problem_explanation_problem_sample_input_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='detailed_verdicts',
            field=models.JSONField(default=list),
        ),
    ]
